import { City } from "@/types/interfaces/constants";

export const DAYS_OF_WEEK: string[] = [
  "Pazartesi",
  "Salı",
  "Çarşamba",
  "Perşembe",
  "Cuma",
  "Cumartesi",
  "Pazar",
];

export const MONTHS: string[] = [
  "Ocak",
  "Şubat",
  "Mart",
  "Nisan",
  "Mayıs",
  "Haziran",
  "Temmuz",
  "Ağustos",
  "Eylül",
  "Ekim",
  "Kasım",
  "Aralık",
];

export const CITIES: City[] = [
  { id: 1, value: "Adana", label: "Adana" },
  { id: 2, value: "Adıyaman", label: "Adıyaman" },
  { id: 3, value: "Afyonkarahisar", label: "Afyonkarahisar" },
  { id: 4, value: "Ağrı", label: "Ağrı" },
  { id: 5, value: "Amasya", label: "Amasya" },
  { id: 6, value: "Ankara", label: "Ankara" },
  { id: 7, value: "Antalya", label: "Antalya" },
  { id: 8, value: "Artvin", label: "Artvin" },
  { id: 9, value: "Aydın", label: "Aydın" },
  { id: 10, value: "Balıkesir", label: "Balıkesir" },
  { id: 11, value: "Bilecik", label: "Bilecik" },
  { id: 12, value: "Bingöl", label: "Bingöl" },
  { id: 13, value: "Bitlis", label: "Bitlis" },
  { id: 14, value: "Bolu", label: "Bolu" },
  { id: 15, value: "Burdur", label: "Burdur" },
  { id: 16, value: "Bursa", label: "Bursa" },
  { id: 17, value: "Çanakkale", label: "Çanakkale" },
  { id: 18, value: "Çankırı", label: "Çankırı" },
  { id: 19, value: "Çorum", label: "Çorum" },
  { id: 20, value: "Denizli", label: "Denizli" },
  { id: 21, value: "Diyarbakır", label: "Diyarbakır" },
  { id: 22, value: "Edirne", label: "Edirne" },
  { id: 23, value: "Elazığ", label: "Elazığ" },
  { id: 24, value: "Erzincan", label: "Erzincan" },
  { id: 25, value: "Erzurum", label: "Erzurum" },
  { id: 26, value: "Eskişehir", label: "Eskişehir" },
  { id: 27, value: "Gaziantep", label: "Gaziantep" },
  { id: 28, value: "Giresun", label: "Giresun" },
  { id: 29, value: "Gümüşhane", label: "Gümüşhane" },
  { id: 30, value: "Hakkari", label: "Hakkari" },
  { id: 31, value: "Hatay", label: "Hatay" },
  { id: 32, value: "Isparta", label: "Isparta" },
  { id: 33, value: "Mersin", label: "Mersin" },
  { id: 34, value: "İstanbul", label: "İstanbul" },
  { id: 35, value: "İzmir", label: "İzmir" },
  { id: 36, value: "Kars", label: "Kars" },
  { id: 37, value: "Kastamonu", label: "Kastamonu" },
  { id: 38, value: "Kayseri", label: "Kayseri" },
  { id: 39, value: "Kırklareli", label: "Kırklareli" },
  { id: 40, value: "Kırşehir", label: "Kırşehir" },
  { id: 41, value: "Kocaeli", label: "Kocaeli" },
  { id: 42, value: "Konya", label: "Konya" },
  { id: 43, value: "Kütahya", label: "Kütahya" },
  { id: 44, value: "Malatya", label: "Malatya" },
  { id: 45, value: "Manisa", label: "Manisa" },
  { id: 46, value: "Kahramanmaraş", label: "Kahramanmaraş" },
  { id: 47, value: "Mardin", label: "Mardin" },
  { id: 48, value: "Muğla", label: "Muğla" },
  { id: 49, value: "Muş", label: "Muş" },
  { id: 50, value: "Nevşehir", label: "Nevşehir" },
  { id: 51, value: "Niğde", label: "Niğde" },
  { id: 52, value: "Ordu", label: "Ordu" },
  { id: 53, value: "Rize", label: "Rize" },
  { id: 54, value: "Sakarya", label: "Sakarya" },
  { id: 55, value: "Samsun", label: "Samsun" },
  { id: 56, value: "Siirt", label: "Siirt" },
  { id: 57, value: "Sinop", label: "Sinop" },
  { id: 58, value: "Sivas", label: "Sivas" },
  { id: 59, value: "Tekirdağ", label: "Tekirdağ" },
  { id: 60, value: "Tokat", label: "Tokat" },
  { id: 61, value: "Trabzon", label: "Trabzon" },
  { id: 62, value: "Tunceli", label: "Tunceli" },
  { id: 63, value: "Şanlıurfa", label: "Şanlıurfa" },
  { id: 64, value: "Uşak", label: "Uşak" },
  { id: 65, value: "Van", label: "Van" },
  { id: 66, value: "Yozgat", label: "Yozgat" },
  { id: 67, value: "Zonguldak", label: "Zonguldak" },
  { id: 68, value: "Aksaray", label: "Aksaray" },
  { id: 69, value: "Bayburt", label: "Bayburt" },
  { id: 70, value: "Karaman", label: "Karaman" },
  { id: 71, value: "Kırıkkale", label: "Kırıkkale" },
  { id: 72, value: "Batman", label: "Batman" },
  { id: 73, value: "Şırnak", label: "Şırnak" },
  { id: 74, value: "Bartın", label: "Bartın" },
  { id: 75, value: "Ardahan", label: "Ardahan" },
  { id: 76, value: "Iğdır", label: "Iğdır" },
  { id: 77, value: "Yalova", label: "Yalova" },
  { id: 78, value: "Karabük", label: "Karabük" },
  { id: 79, value: "Kilis", label: "Kilis" },
  { id: 80, value: "Osmaniye", label: "Osmaniye" },
  { id: 81, value: "Düzce", label: "Düzce" },
];
